### ISSUE TITLE
Create Idle Sprites

### ISSUE THREAD

**Issue by XoXPsychoSisXoX** [TJsDevServer/GameOff2019#100]
Create sprites for idling.

**Comment by BradicalTS** [comment]
![Dr Geribaldi concept](https://user-images.githubusercontent.com/59863807/72751504-02ac0480-3b7d-11ea-9ff7-065d3eee4027.png)

**Comment by BradicalTS** [comment]
framesize: 42x74
![Dr Geribaldi upscaled](https://user-images.githubusercontent.com/59863807/73093767-72333400-3e9c-11ea-86ab-fc62d8dd5ddc.png)
