### ISSUE TITLE
Create Enemy Concepts

### ISSUE THREAD

**Issue by XoXPsychoSisXoX** [TJsDevServer/GameOff2019#124]
Create designs/concepts of various enemies belonging to the different dimensions.

**Comment by HogeFG** [comment]
![glider_snake](https://user-images.githubusercontent.com/59732840/72481308-dd17a780-37d8-11ea-8c08-b548a00c2545.png)
![legs_in_a_shell](https://user-images.githubusercontent.com/59732840/72481309-dd17a780-37d8-11ea-95eb-1829a5af7d10.png)
![leviathan](https://user-images.githubusercontent.com/59732840/72481310-dd17a780-37d8-11ea-86c2-752860ee8937.png)
![muddy_water_blob](https://user-images.githubusercontent.com/59732840/72481311-ddb03e00-37d8-11ea-87b2-718a012970f7.png)
![pebble_eater](https://user-images.githubusercontent.com/59732840/72481312-ddb03e00-37d8-11ea-9713-cac123f2db57.png)
![pooffer_moose](https://user-images.githubusercontent.com/59732840/72481313-ddb03e00-37d8-11ea-87c9-255163084aa2.png)
![puffing_plants](https://user-images.githubusercontent.com/59732840/72481314-ddb03e00-37d8-11ea-9fd3-6a66f1426710.png)
![clouds](https://user-images.githubusercontent.com/59732840/72481315-de48d480-37d8-11ea-8a24-a765a52599bf.png)

**Comment by HogeFG** [comment]
![muddy_water_blob](https://user-images.githubusercontent.com/59732840/72481520-8eb6d880-37d9-11ea-9707-445b9efd2133.png)
[muddy_water_blob.zip](https://github.com/PerpetualMotionGames/TheHairQuest/files/4068333/muddy_water_blob.zip)

**Comment by HogeFG** [comment]
[glider_snake.zip](https://github.com/PerpetualMotionGames/TheHairQuest/files/4068338/glider_snake.zip)
![glider_snake](https://user-images.githubusercontent.com/59732840/72481577-b86fff80-37d9-11ea-9274-d0b7c382a6ba.png)

**Comment by HogeFG** [comment]
![pebble_eater](https://user-images.githubusercontent.com/59732840/72481614-d8072800-37d9-11ea-9dc6-2d6be6b55cb0.png)
[pebble_eater.zip](https://github.com/PerpetualMotionGames/TheHairQuest/files/4068345/pebble_eater.zip)

**Comment by HogeFG** [comment]
![clouds](https://user-images.githubusercontent.com/59732840/72481710-25839500-37da-11ea-8e7d-e59732cf8e42.png)
[clouds.zip](https://github.com/PerpetualMotionGames/TheHairQuest/files/4068355/clouds.zip)

**Comment by HogeFG** [comment]
![legs_in_a_shell](https://user-images.githubusercontent.com/59732840/72481782-4a780800-37da-11ea-8875-b9e0bbaff1fe.png)
[legs_in_a_shell.zip](https://github.com/PerpetualMotionGames/TheHairQuest/files/4068377/legs_in_a_shell.zip)

**Comment by HogeFG** [comment]
![pooffer_moose](https://user-images.githubusercontent.com/59732840/72481823-67acd680-37da-11ea-97d3-acd53197d7be.png)
[pooffer_moose.zip](https://github.com/PerpetualMotionGames/TheHairQuest/files/4068386/pooffer_moose.zip)

**Comment by HogeFG** [comment]
![puffing_plants](https://user-images.githubusercontent.com/59732840/72481859-89a65900-37da-11ea-8432-5bbd8ca4161e.png)
[puffing_plant.zip](https://github.com/PerpetualMotionGames/TheHairQuest/files/4068392/puffing_plant.zip)

**Comment by HogeFG** [comment]
![leviathan](https://user-images.githubusercontent.com/59732840/72481896-a478cd80-37da-11ea-806d-581392fe1afb.png)
[leviathan.zip](https://github.com/PerpetualMotionGames/TheHairQuest/files/4068396/leviathan.zip)

**Comment by HogeFG** [comment]
![showcase](https://user-images.githubusercontent.com/59732840/72789841-376a9b00-3c13-11ea-9716-391a851e1ed0.png)
[hot_nugget.zip](https://github.com/PerpetualMotionGames/TheHairQuest/files/4090090/hot_nugget.zip)

**Comment by HogeFG** [comment]
![showcase](https://user-images.githubusercontent.com/59732840/72789944-5f59fe80-3c13-11ea-9a53-1ff05dc38692.png)
[skelefish.zip](https://github.com/PerpetualMotionGames/TheHairQuest/files/4090099/skelefish.zip)

**Comment by HogeFG** [comment]
![showcase](https://user-images.githubusercontent.com/59732840/72789992-7b5da000-3c13-11ea-994f-a4253129f84b.png)
[magma_slug.zip](https://github.com/PerpetualMotionGames/TheHairQuest/files/4090101/magma_slug.zip)

**Comment by HogeFG** [comment]
![showcase](https://user-images.githubusercontent.com/59732840/72790030-8e707000-3c13-11ea-84c8-d48b93e628f2.png)
[fire_tick.zip](https://github.com/PerpetualMotionGames/TheHairQuest/files/4090103/fire_tick.zip)

**Comment by HogeFG** [comment]
![showcase](https://user-images.githubusercontent.com/59732840/72790090-ab0ca800-3c13-11ea-9b14-f569e509254e.png)
[centipede_platform.zip](https://github.com/PerpetualMotionGames/TheHairQuest/files/4090107/centipede_platform.zip)

**Comment by HogeFG** [comment]
![showcase](https://user-images.githubusercontent.com/59732840/72790172-d98a8300-3c13-11ea-9bba-460eb1565998.png)
[volcano.zip](https://github.com/PerpetualMotionGames/TheHairQuest/files/4090112/volcano.zip)

**Comment by HogeFG** [comment]
![floating_fluff](https://user-images.githubusercontent.com/59732840/73129450-6e99cd00-3fc2-11ea-9b82-d515753c88e9.png)
![jelly](https://user-images.githubusercontent.com/59732840/73129451-6f326380-3fc2-11ea-9732-67780ea94dd5.png)

**Comment by HogeFG** [comment]
![blob](https://user-images.githubusercontent.com/59732840/73129453-82453380-3fc2-11ea-869c-d89be0861a71.png)

**Comment by HogeFG** [comment]
![pond_worm](https://user-images.githubusercontent.com/59732840/73129454-8e30f580-3fc2-11ea-914f-835139cc4433.png)
![boulder](https://user-images.githubusercontent.com/59732840/73129455-8e30f580-3fc2-11ea-9ec6-1083cd902f5b.png)
![moss_worm](https://user-images.githubusercontent.com/59732840/73129456-8e30f580-3fc2-11ea-86fc-60a1ebe34192.png)
![swamp_goblin](https://user-images.githubusercontent.com/59732840/73129457-8e30f580-3fc2-11ea-98f3-851628adbb20.png)
![walking_skull](https://user-images.githubusercontent.com/59732840/73129458-8ec98c00-3fc2-11ea-9547-5b73c7433cb1.png)
![fungi_folk](https://user-images.githubusercontent.com/59732840/73129459-8ec98c00-3fc2-11ea-8757-ffd98bd9cae5.png)
![wasp](https://user-images.githubusercontent.com/59732840/73129460-8ec98c00-3fc2-11ea-9383-4c8fbb68c2e4.png)
![ugly_snake](https://user-images.githubusercontent.com/59732840/73129461-8ec98c00-3fc2-11ea-8c4b-62ab0cd29630.png)

**Comment by HogeFG** [comment]
![patroller](https://user-images.githubusercontent.com/59732840/73419590-72995800-42fe-11ea-9c90-d8e792bf00b0.png)
![surveillance](https://user-images.githubusercontent.com/59732840/73419592-7331ee80-42fe-11ea-9822-febc4f6c280b.png)
![steam_pipe](https://user-images.githubusercontent.com/59732840/73419605-7e851a00-42fe-11ea-9e43-7abea04fde2a.png)
![oil_pipe](https://user-images.githubusercontent.com/59732840/73419606-7e851a00-42fe-11ea-91f9-3c749b16cb23.png)
![butler](https://user-images.githubusercontent.com/59732840/73419612-85ac2800-42fe-11ea-82c1-7a10ab645913.png)
![windup_doll](https://user-images.githubusercontent.com/59732840/73419613-85ac2800-42fe-11ea-8640-2044d3d24e2b.png)
![sweeper](https://user-images.githubusercontent.com/59732840/73419614-85ac2800-42fe-11ea-92fd-36fb88850cb6.png)
![burst_turret](https://user-images.githubusercontent.com/59732840/73419627-8e9cf980-42fe-11ea-802b-b160600b283b.png)
![tesla_gun](https://user-images.githubusercontent.com/59732840/73419628-8e9cf980-42fe-11ea-9beb-f1fada28cd35.png)
![fire_cannon](https://user-images.githubusercontent.com/59732840/73419629-8e9cf980-42fe-11ea-8e2d-66077bd8849c.png)
