### ISSUE TITLE
Need a tutorial level

### ISSUE THREAD

**Issue by TJSteel** [TJsDevServer/GameOff2019#16]
This task is to create a tutorial level

I'd suggest having some messages for the player along the way to explain which buttons need to be pressed, either a signpost, or something UI based I'm not sure

**Comment by KatieLG** [comment]
Have a basic tutorial level in place - will tinker with the placement of the world space UI to see what looks best

**Comment by KatieLG** [comment]
Have a basic tutorial level in place - will tinker with the placement of the world space UI to see what looks best
