### ISSUE TITLE
Level management

### ISSUE THREAD

**Issue by TJSteel** [TJsDevServer/GameOff2019#17]
Need to find out how to do level management,

keeping the critical level items such as tilemaps, the player etc, sync'd are going to be key to making this simple to use.

**Comment by TJSteel** [comment]
This issue is almost complete, all shared game items are now prefabs

Next stage is to incorporate the transition from one level to another and keep the player stats in tact (anything like health, points, etc)

**Comment by KatieLG** [comment]
The main system is now in place - all that remains is keeping track of the index of the first level either by names or manually.
